// ⬅️  Inserisci qui la lista dei file (presa da Cloudflare R2 → Objects → copia nomi)
module.exports = [
  "001. Taylor Swift - The Fate of Ophelia.mp3",
"002. HUNTRX, EJAE, Audrey Nuna, REI AMI & KPop Demon Hunters Cast - Golden.mp3",
"003. Alex Warren - Ordinary.mp3",
"004. Olivia Dean - Man I Need.mp3",
"005. Taylor Swift - Opalite.mp3",
"006. Leon Thomas - MUTT.mp3",
"007. Justin Bieber - DAISIES.mp3",
"008. Mariah Carey - All I Want for Christmas Is You.mp3",
"009. Kehlani - Folded.mp3",
"01. Alanis Morissette - Ironic (2015 Remaster).mp3",
"01. Drake - Toosie Slide.mp3",
"01. James Blunt - You’re Beautiful.mp3",
"01. Luis Fonsi, Daddy Yankee - Despacito ft. Justin Bieber.mp3",
"01. Madonna - La Isla Bonita.mp3",
"01. Michael Jackson - Don't Stop 'Til You Get Enough.mp3",
"01. Michael Jackson - Wanna Be Startin' Somethin'.mp3",
"010. Morgan Wallen - I Got Better.mp3",
"011. Wham! - Last Christmas.mp3",
"012. sombr - back to friends.mp3",
"013. Brenda Lee - Rockin' Around The Christmas Tree.mp3",
"014. Bobby Helms - Jingle Bell Rock.mp3",
"015. Morgan Wallen - What I Want.mp3",
"016. Ella Langley - Choosin' Texas.mp3",
"017. Chris Brown - It Depends (feat. Bryson Tiller).mp3",
"018. Olivia Dean - So Easy (To Fall In Love).mp3",
"019. Ariana Grande - Santa Tell Me.mp3",
"02. Alphaville - Forever Young.mp3",
"02. Coldplay - Viva La Vida.mp3",
"02. DJ Khaled - Wild Thoughts (feat. Rihanna & Br.mp3",
"02. Michael Jackson -  Baby Be Mine.mp3",
"02. Michael Jackson - Rock With You.mp3",
"02. Red Hot Chili Peppers - Under the Bridge.mp3",
"020. Sabrina Carpenter - Manchild.mp3",
"021. Saja Boys, Andrew Choi, Neckwav, Danny Chung, Kevin Woo & samUIL Lee  - Soda Pop.mp3",
"022. Sabrina Carpenter - Tears.mp3",
"023. Ravyn Lenae - Love Me Not.mp3",
"024. Saja Boys, Andrew Choi, Neckwav, Danny Chung, Kevin Woo & samUIL Lee - Your Idol.mp3",
"025. Cody Johnson - Travelin' Soldier.mp3",
"026. Tate McRae - TIT FOR TAT.mp3",
"027. Kelly Clarkson - Underneath the Tree.mp3",
"028. Taylor Swift - Elizabeth Taylor.mp3",
"029. Nat King Cole - The Christmas Song (Merry Christmas To You) (Remastered 1999).mp3",
"03. French Montana - Unforgettable (feat. Swae Lee).mp3",
"03. Madonna - Vogue.mp3",
"03. Michael Jackson - The Girl Is Mine.mp3",
"03. Michael Jackson - Working Day And Night.mp3",
"03. Red Hot Chili Peppers - Can’t Stop.mp3",
"03. Tina Turner - The Best.mp3",
"030. Andy Williams - It's the Most Wonderful Time of the Year.mp3",
"031. KATSEYE - Gabriela.mp3",
"032. Michael Bublé - It's Beginning to Look a Lot like Christmas.mp3",
"033. Riley Green - Don't Mind If I Do (feat. Ella Langley).mp3",
"034. Dean Martin - Let It Snow! Let It Snow! Let It Snow!.mp3",
"035. NF - FEAR.mp3",
"036. HUNTR_X, EJAE, Audrey Nuna & REI AMI - How It’s Done.mp3",
"037. The Ronettes - Sleigh Ride.mp3",
"038. Megan Moroney - 6 Months Later.mp3",
"039. Lainey Wilson - Somewhere Over Laredo.mp3",
"04. A-Ha - Take On Me.mp3",
"04. Gym Class Heroes - Cupid’s Chokehold  Breakfast in America.mp3",
"04. Imagine Dragons - Believer.mp3",
"04. Michael Jackson - Get On The Floor.mp3",
"04. Michael Jackson - Thriller.mp3",
"04. THE GOO GOO DOLLS - Iris.mp3",
"040. Burl Ives - A Holly Jolly Christmas.mp3",
"041. Disco Lines & Tinashe - No Broke Boys.mp3",
"042. HUNTRX, EJAE, Audrey Nuna, REI AMI & KPop Demon Hunters Cast - What It Sounds Like.mp3",
"043. Russell Dickerson - Happen To Me (feat. Jonas Brothers).mp3",
"044. Taylor Swift - Wi$h Li$t.mp3",
"045. Gunna - wgft (feat. Burna Boy).mp3",
"046. Taylor Swift - Father Figure.mp3",
"047. Raye - WHERE IS MY HUSBAND!.mp3",
"048. Darlene Love - Christmas (Baby Please Come Home).mp3",
"049. José Feliciano - Feliz Navidad.mp3",
"05. Charlie Puth - Attention.mp3",
"05. Cher - Believe.mp3",
"05. Linkin Park - In the End.mp3",
"05. Michael Jackson - Beat It.mp3",
"05. Michael Jackson - Off The Wall.mp3",
"05. Michael McDonald - I Keep Forgettin (Every Time You're Near).mp3",
"050. Morgan Wallen - 20 Cigarettes.mp3",
"051. BigXthaPlug - Hell At Night (feat. Ella Langley).mp3",
"052. Justin Bieber - YUKON.mp3",
"053. Tame Impala - Dracula.mp3",
"054. Mariah the Scientist & Kali Uchis - Is It a Crime.mp3",
"055. Olivia Dean - A Couple Minutes.mp3",
"056. Myles Smith - Nice To Meet You.mp3",
"057. Hudson Westbrook - House Again.mp3",
"058. Summer Walker - Robbed You.mp3",
"059. Chase Matthew - Darlin'.mp3",
"06. Daniel Powter - Bad Day.mp3",
"06. Michael Jackson -  Billie Jean.mp3",
"06. Michael Jackson - Girlfriend.mp3",
"06. Pet Shop Boys - West End Girls.mp3",
"06. Shawn Mendes -There's Nothing Holdin' Me Back.mp3",
"06. Third Eye Blind - Semi-charmed Life (2006 Remaster).mp3",
"060. Summer Walker, Latto & Doja Cat - Go Girl.mp3",
"061. YoungBoy Never Broke Again - Shot Callin.mp3",
"062. NF - WHO I WAS.mp3",
"063. Max McNown - Better Me For You (Brown Eyes).mp3",
"064. Taylor Swift - The Life of a Showgirl.mp3",
"065. Luke Combs - Back in the Saddle.mp3",
"066. Cardi B - ErrTime.mp3",
"067. Doja Cat - Jealous Type.mp3",
"068. Summer Walker - Baby.mp3",
"069. Summer Walker - No.mp3",
"07. Bruno Mars - Thats What I Like.mp3",
"07. David Guetta - Sexy Bitch (feat. Akon).mp3",
"07. Diddy - I’ll Be Missing You (feat. Faith Evans & 112).mp3",
"07. Duran Duran - Girls on Film (2010 Remaster).mp3",
"07. Michael Jackson - Human Nature.mp3",
"07. Michael Jackson - She's Out Of My Life.mp3",
"070. NF - SORRY.mp3",
"071. Gavin Adcock - Last One To Know.mp3",
"072. sombr - 12 to 12.mp3",
"073. Tyler, The Creator - Sugar On My Tongue.mp3",
"074. Metro Boomin, Quavo, Breskii, YKNIECE & DJ SPINZ - Take Me Thru Dere.mp3",
"075. Cody Johnson - The Fall.mp3",
"076. Taylor Swift - Ruin The Friendship.mp3",
"077. Taylor Swift - Wood.mp3",
"078. Taylor Swift - Actually Romantic.mp3",
"079. Summer Walker - FMT.mp3",
"08. Cardi B - Bodak Yellow.mp3",
"08. Green Day - American Idiot.mp3",
"08. Matchbox Twenty - Push.mp3",
"08. Michael Jackson - I Can't Help It.mp3",
"08. Michael Jackson - P.Y.T. (Pretty Young Thing).mp3",
"08. Whitesnake - Here I Go Again 87 (2018 Remaster).mp3",
"080. Summer Walker - 1-800 Heartbreak.mp3",
"081. Taylor Swift - Eldest Daughter.mp3",
"082. Olivia Dean - Nice To Each Other.mp3",
"083. Parker McCollum - What Kinda Man.mp3",
"084. G Herbo - Went Legit.mp3",
"085. NF - GIVE ME A REASON.mp3",
"086. NF - HOME.mp3",
"087. Cardi B - Safe (feat. Kehlani).mp3",
"088. Coldplay - Sparks.mp3",
"089. Taylor Swift - CANCELLED!.mp3",
"09. Chaka Khan - I Feel for You.mp3",
"09. Ed Sheeran - Shape Of You.mp3",
"09. Mark Morrison - Return of the Mack (C & J Street Mix).mp3",
"09. Michael Jackson - It's The Falling In Love.mp3",
"09. Michael Jackson - The Lady In My Life.mp3",
"09. Uncle Kracker - Follow Me.mp3",
"090. Lady Gaga - The Dead Dance.mp3",
"091. Sabrina Carpenter - When Did You Get Hot_.mp3",
"092. The Marías - Sienna.mp3",
"093. Ed Sheeran - Camera.mp3",
"094. Luke Combs - Days Like These.mp3",
"095. Shaboozey & Jelly Roll - Amen.mp3",
"096. Summer Walker, Glorilla, Sexyy Red & Monaleo - Baller.mp3",
"097. Olivia Dean - Let Alone The One You Love.mp3",
"098. Hazbin Hotel - Losin' Streak.mp3",
"099. Hardy - Favorite Country Song.mp3",
"10. Big Mountain - Baby, I Love Your Way.mp3",
"10. DJ Khaled - I'm the One (feat. Justin B, Quavo,& Lil Wayne).mp3",
"10. Fleetwood Mac - Everywhere (2018 Remaster).mp3",
"10. Madonna - 4 Minutes (feat. Justin Timberlake & Timbaland).mp3",
"10. Michael Jackson - Burn This Disco Out.mp3",
"100. Jason Aldean - How Far Does A Goodbye Go.mp3",
"100. Nicky Jam - El Amante.mp3",
"100. Quad City DJ's - C'mon n' Ride It (The Train) [Radio Edit].mp3",
"100. Trick Daddy - Let's Go (feat. Big D & Twista).mp3",
"11. Matchbox Twenty - Unwell.mp3",
"11. Roxette - Joyride.mp3",
"11. Sam Hunt - Body Like a Back Road.mp3",
"11. Spandau Ballet - True.mp3",
"12. 21 Savage - Bank Account.mp3",
"12. Brandy - The Boy Is Mine (Radio Edit).mp3",
"12. Chicago - Hard to Say I’m Sorry.mp3",
"12. Missy Elliott - Work It.mp3",
"13. Childish Gambino - Redbone.mp3",
"13. Donna Lewis - I Love You Always Forever.mp3",
"13. Panic! At The Disco - I Write Sins Not Tragedies.mp3",
"13. Starship - Nothing's Gonna Stop Us Now.mp3",
"14. All Saints - Pure Shores.mp3",
"14. Post Malone - Congratulations feat. Quavo.mp3",
"14. Simply Red - Holding Back the Years.mp3",
"14. Simply Red - Something Got Me Started.mp3",
"15. Liam Payne - Strip That Down (feat. Quavo).mp3",
"15. Nickelback - How You Remind Me.mp3",
"15. The Notorious B.I.G. - Hypnotize (2014 Remaster).mp3",
"15. Yes - Owner of a Lonely Heart.mp3",
"16. George Benson - Give Me the Night.mp3",
"16. Kendrick Lamar - HUMBLE..mp3",
"16. The Corrs - Breathless.mp3",
"16. Tina Turner - Goldeneye.mp3",
"17. B.O.B - Nothin’ on You (feat. Bruno Mars).mp3",
"17. Foreigner - I Want to Know What Love Is (1999 Remaster).mp3",
"17. Marc Cohn - Walking in Memphis.mp3",
"17. Niall Horan - Slow Hands.mp3",
"18. Jason Mraz - Lucky.mp3",
"18. John Parr - St. Elmo's Fire (Man in Motion).mp3",
"18. Lil Uzi Vert - XO TOUR Llif3.mp3",
"18. Seal - Kiss from a Rose.mp3",
"19. All Saints - Never Ever (Radio Edit).mp3",
"19. Iyaz - Replay (feat. Flo Rida).mp3",
"19. The Cars - Drive.mp3",
"19. The Chainsmokers & Coldplay - Something Just Like This.mp3",
"20. Blur - Song 2 (2012 Remaster).mp3",
"20. Gorillaz - Feel Good Inc.mp3",
"20. Roxette - The Look.mp3",
"20. Zedd - Stay (Feat Alessia Cara).mp3",
"21. Calvin Harris - Feels (feat. Pharrell Williams, Katy Perry & Big Sean).mp3",
"21. Kid Rock - All Summer Long.mp3",
"21. The Proclaimers - I'm Gonna Be (500 Miles).mp3",
"21. Tori Amos - Cornflake Girl.mp3",
"22. Deee-Lite - Groove Is in the Heart.mp3",
"22. Faith Hill - There You’ll Be (2007 Remaster).mp3",
"22. Talk Talk - It's My Life.mp3",
"22. Yo Gotti - Rake It Up (feat. Nicki Minaj).mp3",
"23. Duran Duran - Ordinary World.mp3",
"23. Flo Rida - Low (feat. T-Pain).mp3",
"23. J Balvin & Willy William - Mi Gente.mp3",
"23. New Order - Blue Monday '88 (2015 Remaster).mp3",
"24. En Vogue - Don't Let Go (Love).mp3",
"24. Kesha - Praying.mp3",
"24. Michelle Branch - Everywhere.mp3",
"24. Rod Stewart - Baby Jane.mp3",
"25. 3Oh!3 - DONTTRUSTME.mp3",
"25. Al Jarreau - We’re in This Love Together.mp3",
"25. Future - Mask Off.mp3",
"25. Green Day - Good Riddance (Time of Your Life).mp3",
"26. Halsey - Now Or Never.mp3",
"26. Limahl - Never Ending Story (Giorgio 7 Mix).mp3",
"26. Michael Bublé - Feeling Good.mp3",
"26. Rod Stewart - Have I Told You Lately.mp3",
"27. James Arthur - Say You Won't Let Go.mp3",
"27. Peter Andre - Mysterious Girl (Radio Edit).mp3",
"27. Peter Cetera - Glory of Love.mp3",
"27. Sean Paul - Temperature.mp3",
"28. Bette Midler - Wind Beneath My Wings.mp3",
"28. Dante Thomas - Miss California.mp3",
"28. Demi Lovato - Sorry Not Sorry.mp3",
"28. Stone Temple Pilots - Interstate Love Song.mp3",
"29. Joey Scarbury - Believe It or Not (From Greatest American Hero).mp3",
"29. Khalid - location.mp3",
"29. Paolo Nutini - Last Request.mp3",
"29. Robin S - Show Me Love.mp3",
"30. Faith Hill - This Kiss.mp3",
"30. Portugal. The Man - Feel It Still.mp3",
"30. Starpoint - Object of My Desire.mp3",
"30. Wayne Wonder - No Letting Go.mp3",
"31. All-4-One - I Swear.mp3",
"31. Climie Fisher - Love Changes (Everything).mp3",
"31. Kygo & Selena Gomez -  It Ain't Me.mp3",
"31. P.O.D. - Youth of the Nation.mp3",
"32. Cassie - Me & U.mp3",
"32. Kendrick Lamar - LOYALTY. (FEAT. RIHANNA.).mp3",
"32. Robert Palmer - Simply Irresistible.mp3",
"32. Tasmin Archer - Sleeping Satellite.mp3",
"33. (Snow) - Informer.mp3",
"33. Alanis Morissette - Hands Clean.mp3",
"33. Ed Sheeran - Castle On The Hill.mp3",
"33. Laura Branigan - Self Control.mp3",
"34. Barenaked Ladies - One Week.mp3",
"34. Gucci Mane - Lemonade.mp3",
"34. Nu Shooz - I Can’t Wait.mp3",
"34. Playboi Carti - Magnolia.mp3",
"35. Adina Howard - Freak Like Me (Radio Edit).mp3",
"35. James Ingram - There’s No Easy Way.mp3",
"35. Paramore - The Only Exception.mp3",
"35. SZA - Love Galore (feat. Travis Scott).mp3",
"36. 98º - Only Wanna Be with You.mp3",
"36. Ashley Tisdale - He Said She Said.mp3",
"36. Jane Child - Don’t Wanna Fall in Love.mp3",
"36. YFN Lucci - Everyday We Lit (feat. PnB Rock).mp3",
"37. Chris Rea - Looking for the Summer.mp3",
"37. Migos- Slippery (feat. Gucci Mane).mp3",
"37. My Chemical Romance - Teenagers.mp3",
"37. Narada Michael Walden - Gimme Gimme Gimme (feat. Patti Austin).mp3",
"38. Brandy - Full Moon.mp3",
"38. Dustin Lynch - Small Town Boy.mp3",
"38. Eddi Reader - Patience of Angels.mp3",
"38. Peter Schilling - Major Tom (Coming Home).mp3",
"39. A Boogie Wit da Hoodie - Drowning (feat. Kodak Black.mp3",
"39. Blake Shelton - Honey Bee.mp3",
"39. The Time - Jungle Love.mp3",
"39. Vitamin C - Graduation (Friends Forever).mp3",
"40. Kane Brown - What Ifs.mp3",
"40. Lil' Kim - Crush on You.mp3",
"40. Los Lobos - La Bamba.mp3",
"40. Paris Hilton - Stars Are Blind.mp3",
"41. Brett Young - In Case You Didn't Know.mp3",
"41. Chris Rea - On the Beach.mp3",
"41. Faith No More - Easy.mp3",
"41. Lupe Fiasco - Superstar (feat. Matthew Santos).mp3",
"42. Cheat Codes - No Promises (feat. Demi Lovato).mp3",
"42. Eternal - I Wanna Be the Only One (feat. BeBe Winans).mp3",
"42. Hot Chocolate - It Started with a Kiss.mp3",
"42. Kevin Lyttle - Turn Me On.mp3",
"43. Biffy Clyro - Many of Horror.mp3",
"43. Bruno Mars - Versace on the Floor.mp3",
"43. Duncan Sheik - Barely Breathing.mp3",
"43. The Pretenders - Don't Get Me Wrong.mp3",
"44. Jaheim - Put That Woman First.mp3",
"44. Julia Michaels - Issues.mp3",
"44. New Order - Regret.mp3",
"44. Randy Crawford - You Might Need Somebody.mp3",
"45. Color Me Badd - I Wanna Sex You Up.mp3",
"45. David Guetta - 2U (feat. Justin Bieber).mp3",
"45. The B-52's - Love Shack.mp3",
"45. THE GOO GOO DOLLS - Sympathy.mp3",
"46. 2 Chainz - It's a Vibe (Ft. Ty Dolla Sign, Trey Songz & Jhene Aiko).mp3",
"46. A-Ha - Summer Moved On.mp3",
"46. Damn Yankees - High Enough.mp3",
"46. Nick Kamen - Each Time You Break My Heart.mp3",
"47. Carolina Liar - Show Me What I’m Looking For.mp3",
"47. Jane’s Addiction - Jane Says.mp3",
"47. Pet Shop Boys - Go West (2003 Remaster).mp3",
"47. Selena Gomez - Fetish (feat. Gucci Mane).mp3",
"48. Air Supply - Goodbye.mp3",
"48. Carl Thomas - I Wish.mp3",
"48. Midland - Drinkin Problem.mp3",
"48. Sister Sledge - Frankie.mp3",
"49. Citizen King - Better Days (And the Bottom Drops Out).mp3",
"49. Cliff Richard - Ocean Deep (2002 Remaster).mp3",
"49. Cobra Starship - Good Girls Go Bad.mp3",
"49. Khalid - Young Dumb & Broke.mp3",
"50. Lily Allen - Smile.mp3",
"50. Lindsey Buckingham - Holiday Road (2024 Remaster).mp3",
"50. Logic - 1-800-273-8255.mp3",
"50. Missy Elliott - The Rain (Supa Dupa Fly).mp3",
"51. Adrian Gurvitz - Classic (Radio Edit).mp3",
"51. Chiddy Bang - Opposite of Adults.mp3",
"51. Old Dominion - No Such Thing as a Broken Heart.mp3",
"51. The Rembrandts - Just the Way It Is, Baby.mp3",
"52. Billy Currington - Do I Make You Wanna.mp3",
"52. Joy Division - Love Will Tear Us Apart.mp3",
"52. Simple Plan - I’m Just a Kid.mp3",
"52. The Pretenders - I’ll Stand by You.mp3",
"53. Barenaked Ladies - Pinch Me.mp3",
"53. Electronic - Getting Away with It.mp3",
"53. Imagine Dragons - Thunder.mp3",
"53. Stevie Nicks - Edge of Seventeen (2016 Remaster).mp3",
"54. 112 - Peaches & Cream (feat. Diddy).mp3",
"54. Debbie Gibson - Lost in Your Eyes.mp3",
"54. Jon Pardi - Heartache on the Dance Floor.mp3",
"54. MC Lyte - Cold Rock a Party.mp3",
"55. Death Cab For Cutie - I Will Follow You into the Dark.mp3",
"55. Kajagoogoo - Too Shy (2004 Remaster).mp3",
"55. The Corrs - What Can I Do (Tin Tin Out Remix).mp3",
"55. Travis Scott - Butterfly Effect.mp3",
"56. Cole Swindell - Flatliner (feat. Dierks Bentley).mp3",
"56. Dusty Springfield - In Private.mp3",
"56. Edwin McCain - I’ll Be.mp3",
"56. John Michael Montgomery - Letters from Home.mp3",
"57. A Rocket To The Moon - Like We Used To.mp3",
"57. LSG - My Body.mp3",
"57. Meek Mill - Whatever You Need (feat. Chris Brown & Ty Dolla $ign).mp3",
"57. Talking Heads - This Must Be the Place (Naive Melody) [2005 Remaster].mp3",
"58. Danity Kane - Damaged.mp3",
"58. GoldLink - Crew (feat. Brent Faiyaz & Shy Gl.mp3",
"58. Nick Kamen - I Promised Myself.mp3",
"58. Peabo Bryson - If Ever You're in My Arms Again.mp3",
"59. Hard-Fi - Hard to Beat (Radio Edit).mp3",
"59. Kendrick Lamar - DNA..mp3",
"59. Lene Marlin - Sitting Down Here.mp3",
"59. The Smiths - This Charming Man (2011 Remaster).mp3",
"60. Eric Benét - Georgy Porgy (feat. Faith Evans).mp3",
"60. Hailee Steinfeld - Most Girl.mp3",
"60. Ryan Cabrera - True.mp3",
"60. The Blues Brothers - Everybody Needs Somebody to Love.mp3",
"61. Lil' Kim - Magic Stick.mp3",
"61. Maluma - Felices los 4.mp3",
"61. Ramones - Baby, I Love You.mp3",
"61. They Might Be Giants - Birdhouse in Your Soul.mp3",
"62. Julee Cruise - Falling.mp3",
"62. Karyn White - Superwoman.mp3",
"62. Louis Tomlinson - Back to You (feat. Bebe Rexha & Digital Farm Animals).mp3",
"62. The Darkness - I Believe in a Thing Called Love.mp3",
"63. Geri Halliwell - It’s Raining Men.mp3",
"63. Roberta Flack - Back Together Again (feat. Donny Hathaway).mp3",
"63. Silk - Freak Me.mp3",
"63. Thomas Rhett - Craving You (feat. Maren Morris.mp3",
"64. Faith Evans - I Love You.mp3",
"64. Gina G - Ooh Aah...Just a Little Bit (Motiv8 Radio Edit).mp3",
"64. Justin Moore - Somebody Else Will.mp3",
"64. The Beach Boys - Kokomo.mp3",
"65. Kevin Michael - We All Want The Same Thing (Feat. Lupe Fiasco).mp3",
"65. Ol Dirty Bastard - Shimmy Shimmy Ya.mp3",
"65. Sheila E. - The Glamorous Life, Pt. 1.mp3",
"65. The Weeknd - Reminder.mp3",
"66. Dylan Scott - My Girl.mp3",
"66. Faith No More - Epic (Radio Edit).mp3",
"66. Jamie Walters - Hold On.mp3",
"66. M2M - Pretty Boy.mp3",
"67. AL B. SURE! - Nite and Day.mp3",
"67. Blackbear - Do Re mi.mp3",
"67. Keith Sweat - Twisted.mp3",
"67. Roxette - Milk and Toast and Honey.mp3",
"68. Chad Brock - Yes!.mp3",
"68. Spacehog - In the Meantime.mp3",
"68. The Stranglers - Golden Brown.mp3",
"68. Wisin - Escapate Conmigo (Ft. Ozuna).mp3",
"69. Art Of Noise - Kiss (feat. Tom Jones).mp3",
"69. Lady Antebellum - You Look Good.mp3",
"69. Paula Cole - I Don’t Want to Wait.mp3",
"69. Seal - Love’s Divine.mp3",
"70. Musiq Soulchild - sobeautiful.mp3",
"70. Tay-K - The Race.mp3",
"70. Tevin Campbell - Can We Talk.mp3",
"70. Twisted Sister - We’re Not Gonna Take It.mp3",
"71. Dawn Penn - You Don’t Love Me (No, No, No).mp3",
"71. Dexys - Geno.mp3",
"71. Macklemore - Glorious (feat. Skylar Grey).mp3",
"71. Mêlée - Built to Last.mp3",
"72. Del Tha Funky Homosapien - Mistadobalina.mp3",
"72. Kendrick Lamar - LOVE. (FEAT. ZACARI.).mp3",
"72. Levert - Casanova.mp3",
"72. Mario Winans - I Don't Wanna Know (feat. Enya & Diddy).mp3",
"73. Carlene Carter - Every Little Thing.mp3",
"73. Marillion - Kayleigh (2017 Remaster).mp3",
"73. Miley Cyrus - Malibu.mp3",
"73. Rupee - Tempted to Touch.mp3",
"74. Faith Evans - Love like This.mp3",
"74. Hot Action Cop - Fever for the Flava (Radio Edit).mp3",
"74. Randy Newman - I Love L.A.mp3",
"74. Selena Gomez - Bad Liar.mp3",
"75. C.C. Catch - Strangers by Night.mp3",
"75. D4L - Laffy Taffy.mp3",
"75. Opus III - It’s a Fine Day.mp3",
"75. SZA - The Weekend.mp3",
"76. Jack's Mannequin - Dark Blue (2015 Remaster).mp3",
"76. Kodak Black - Patty Cake.mp3",
"76. Shola Ama - You Might Need Somebody.mp3",
"76. Tanita Tikaram - Twist in My Sobriety.mp3",
"77. Candlebox - Far Behind.mp3",
"77. Diddy - Last Night (feat. Keyshia Cole).mp3",
"77. Roger - I Want to Be Your Man.mp3",
"77. The Chainsmokers - Honest.mp3",
"78. Donald Fagen - I.G.Y.mp3",
"78. Fleetwood Mac - Skies the Limit (2002 Remaster).mp3",
"78. Less Than Jake - The Science of Selling Yourself Short.mp3",
"78. Tee Grizzley - First Day Out.mp3",
"79. Changing Faces - Stroke You Up.mp3",
"79. Chris Brown - Privacy.mp3",
"79. Morcheeba - Otherwise.mp3",
"79. Stacy Lattisaw - Perfect Combination.mp3",
"80. Catatonia - Road Rage (Radio Edit).mp3",
"80. Luke Combs - When It Rains It Pours.mp3",
"80. Richie Havens - Going Back to My Roots.mp3",
"80. Story Of The Year - Until the Day I Die.mp3",
"81. Camila Cabello - OMG (feat. Quavo).mp3",
"81. Fabolous - Into You.mp3",
"81. Grace - Not Over Yet.mp3",
"81. The Dream Academy - Life in a Northern Town.mp3",
"82. David Foster - The Best of Me.mp3",
"82. Junior M.A.F.I.A. - Get Money.mp3",
"82. P!nk - What About Us.mp3",
"82. Staind - It’s Been Awhile.mp3",
"83. Dua Lipa - New Rules.mp3",
"83. Peter Cetera - Feels Like Heaven (feat. Chaka Khan).mp3",
"83. Regina Spektor - Two Birds.mp3",
"83. STEVE ARRINGTON - Feel So Real.mp3",
"84. Jennifer Love Hewitt - No Ordinary Love.mp3",
"84. Marc Almond - Something's Gotten Hold of My Heart.mp3",
"84. Rae Sremmurd - Perplexing Pegasus.mp3",
"84. Third Eye Blind - Crystal Baller.mp3",
"85. China Anne McClain - What's My Name.mp3",
"85. Larry Graham - One in a Million You.mp3",
"85. Nada Surf - Popular.mp3",
"85. Trey Songz - Can’t Help but Wait.mp3",
"86. Echo And The Bunnymen - The Killing Moon.mp3",
"86. Tamia - So into You.mp3",
"86. Thomas Rhett - Unforgettable.mp3",
"86. Tina Turner - Open Arms.mp3",
"87. Dolly Parton - Wildflowers.mp3",
"87. Eric Hutchinson - Rock & Roll.mp3",
"87. Future - You da Baddest (feat. Nicki Minaj).mp3",
"87. Jane’s Addiction - Been Caught Stealing.mp3",
"88. Planet Perfecto Featuring Grace - Bullet in the Gun (Radio Edit).mp3",
"88. Stacey Q - Two of Hearts.mp3",
"88. Tamia - Officially Missing You.mp3",
"88. The Revivalists - Wish I Knew You.mp3",
"89. Jason Aldean - They Don't Know.mp3",
"89. Morcheeba - The Sea.mp3",
"89. The Used - The Taste of Ink.mp3",
"89. Zapp - More Bounce to the Ounce.mp3",
"90. Elvis Costello - Veronica.mp3",
"90. Fifth Harmony - Down (feat. Gucci Mane).mp3",
"90. Katrina And The Waves - Love Shine a Light.mp3",
"90. Pretty Ricky - Grind with Me (Radio Version).mp3",
"91. Brother Beyond - The Harder I Try.mp3",
"91. Brothers Osborne - It Ain't My Fault.mp3",
"91. Jade - Don't Walk Away.mp3",
"91. The Veronicas - Untouched.mp3",
"92. All the Pretty Girls.mp3",
"92. Babylon Zoo - Spaceman (Radio Edit).mp3",
"92. Slave - Watching You.mp3",
"92. Tweet - Oops (Oh My).mp3",
"93. 2 Chainz - 4 AM (Ft. Travis Scott).mp3",
"93. Mase - Feel So Good.mp3",
"93. The Honeydrippers - Sea of Love.mp3",
"93. The Wombats - Let’s Dance to Joy Division.mp3",
"94. Jacquees - B.E.D..mp3",
"94. Jimmy Nail - Ain’t No Doubt.mp3",
"94. Modern Romance - Best Years of Our Lives.mp3",
"94. Twista - Overnight Celebrity.mp3",
"95. Better Than Ezra - Good.mp3",
"95. Billy Talent - Rusted from the Rain.mp3",
"95. London Boys - I'm Gonna Give My Heart.mp3",
"95. Sofia Carson - Chillin' Like a Villain.mp3",
"96. Dove Cameron - It's Goin' Down.mp3",
"96. Elaine Paige - Memory.mp3",
"96. Ironik - Tiny Dancer (Hold Me Closer).mp3",
"96. The Family Stand - Ghetto Heaven.mp3",
"97. Chris Lane - For Her.mp3",
"97. Debra Laws - Very Special.mp3",
"97. Scarlet - Independent Love Song.mp3",
"97. Wiley - Wearing My Rolex (Radio Edit).mp3",
"98. Carly Pearce - Every Little Thing.mp3",
"98. Kym Sims - Too Blind to See It.mp3",
"98. LCD Soundsystem - Daft Punk Is Playing at My House (Radio Edit).mp3",
"98. Matt Bianco - More than I Can Bear.mp3",
"99. Cher - Song for the Lonely.mp3",
"99. Eg And Alice - Indian.mp3",
"99. Havana (feat. Young Thug).mp3",
"99. Jaki Graham - Set Me Free.mp3"
];